[skip changelog] Sync documentation assets with templates
We have assembled a collection of reusable project assets:
https://github.com/arduino/tooling-project-assets
These assets will be used in the repositories of all Arduino tooling projects.

Some significant improvements and standardizations have been made in the upstream "template" assets, and those are
introduced to this repository here.

Notable:

- Use markdownlint to check for common problems and formatting.
- Make link check task Windows compatible
- Streamline website versioning system
- Use modern MkDocs versioning features
- Make command reference generation task Windows compatible
- Consolidate all Python dependency management to Poetry
- Standardize documentation-related task names and deprecate old task names

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -6,15 +6,11 @@ includes:
 tasks:
   docs:gen:commands:
     desc: Generate command reference files
-    dir: ./docsgen
+    deps:
+      - task: go:cli-docs
     cmds:
-      # docs will generate examples using os.Args[0] so we need to call
-      # the generator `arduino-cli`
-      - go build -o arduino-cli
-      # we invoke `arduino-cli` like this instead of `./arduino-cli` to remove
-      # the `./` chars from the examples
-      - PATH=. arduino-cli ../docs/commands
-      - task: general:format-prettier
+      - |
+        echo "WARNING: this task is deprecated. Use go:cli-docs instead"
 
   docs:gen:protobuf:
     desc: Generate markdown contents for protobuffers
@@ -23,54 +19,123 @@ tasks:
       - '{{ default "protoc" .PROTOC_BINARY }} --doc_out=./docs/rpc --doc_opt=markdown,monitor.md --proto_path=rpc ./rpc/cc/arduino/cli/monitor/v1/*.proto'
       - '{{ default "protoc" .PROTOC_BINARY }} --doc_out=./docs/rpc --doc_opt=markdown,settings.md --proto_path=rpc ./rpc/cc/arduino/cli/settings/v1/*.proto'
       - '{{ default "protoc" .PROTOC_BINARY }} --doc_out=./docs/rpc --doc_opt=markdown,debug.md --proto_path=rpc ./rpc/cc/arduino/cli/debug/v1/*.proto'
-      - task: general:format-prettier
 
   docs:gen:
     desc: Generate documentation files
+    deps:
+      - task: docs:generate
     cmds:
-      - task: docs:gen:commands
-      - task: docs:gen:protobuf
+      - |
+        echo "WARNING: this task is deprecated. Use docs:generate instead"
+
+  docs:generate:
+    desc: Create all generated documentation content
+    deps:
+      - task: go:cli-docs
+      - task: protoc:docs
+    cmds:
+      - task: general:format-prettier
 
   docs:build:
     desc: Build documentation website contents
     deps:
-      - docs:gen:commands
-      - docs:gen:protobuf
+      - task: website:check
     cmds:
-      - mkdocs build -s
-
-  docs:publish:
-    desc: Use Mike to build and push versioned docs
-    deps:
-      - docs:gen:commands
-      - docs:gen:protobuf
-    cmds:
-      - mike deploy -u -p -r {{.DOCS_REMOTE}} {{.DOCS_VERSION}} {{.DOCS_ALIAS}}
+      - |
+        echo "WARNING: this task is deprecated. Use website:check instead"
 
   docs:serve:
     desc: Run documentation website locally
     deps:
-      - docs:build
+      - task: website:serve
     cmds:
-      - mkdocs serve
+      - |
+        echo "WARNING: this task is deprecated. Use website:serve instead"
 
   docs:check-links:
     desc: Verifies there are no dead links in documentation
+    deps:
+      - task: markdown:check-links
     cmds:
       - |
-        npx -p markdown-link-check -c '
-        STATUS=0
-        for file in $(find docs -name "*.md") README.md test/README.md client_example/README.md; do
-          markdown-link-check -c markdown-link-check-config.json -q "$file"
-          STATUS=$(( $STATUS + $? ))
-        done
-        exit $STATUS'
+        echo "WARNING: this task is deprecated. Use markdown:check-links instead"
 
   # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-prettier-formatting-task/Taskfile.yml
   general:format-prettier:
     desc: Format all supported files with Prettier
     cmds:
       - npx prettier --write .
+
+  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/deploy-cobra-mkdocs-versioned-poetry/Taskfile.yml
+  go:cli-docs:
+    desc: Generate command line interface reference documentation
+    dir: ./docsgen
+    cmds:
+      # Command examples use os.Args[0] so the docs generation binary must have the same filename as the project
+      - go build -o {{.PROJECT_NAME}}{{exeExt}}
+      # The binary is invoked like this instead of `./{{.PROJECT_NAME}}` to remove the `./` chars from the examples
+      - PATH=. {{.PROJECT_NAME}} ../docs/commands
+
+  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-markdown-task/Taskfile.yml
+  markdown:check-links:
+    desc: Check for broken links
+    deps:
+      - task: docs:generate
+    cmds:
+      - |
+        if [[ "{{.OS}}" == "Windows_NT" ]]; then
+          # npx --call uses the native shell, which makes it too difficult to use npx for this application on Windows,
+          # so the Windows user is required to have markdown-link-check installed and in PATH.
+          if ! which markdown-link-check &>/dev/null; then
+            echo "markdown-link-check not found or not in PATH. Please install: https://github.com/tcort/markdown-link-check#readme"
+            exit 1
+          fi
+          # Default behavior of the task on Windows is to exit the task when the first broken link causes a non-zero
+          # exit status, but it's better to check all links before exiting.
+          set +o errexit
+          STATUS=0
+          # Using -regex instead of -name to avoid Task's behavior of globbing even when quoted on Windows
+          # The odd method for escaping . in the regex is required for windows compatibility because mvdan.cc/sh gives
+          # \ characters special treatment on Windows in an attempt to support them as path separators.
+          for file in $(find . -regex ".*[.]md"); do
+            markdown-link-check \
+              --quiet \
+              --config "./.markdown-link-check.json" \
+              "$file"
+            STATUS=$(( $STATUS + $? ))
+          done
+          exit $STATUS
+        else
+          npx --package=markdown-link-check --call='
+            STATUS=0
+            for file in $(find . -regex ".*[.]md"); do
+              markdown-link-check \
+                --quiet \
+                --config "./.markdown-link-check.json" \
+                "$file"
+              STATUS=$(( $STATUS + $? ))
+            done
+            exit $STATUS
+          '
+        fi
+
+  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-markdown-task/Taskfile.yml
+  markdown:fix:
+    desc: Automatically correct linting violations in Markdown files where possible
+    cmds:
+      - npx markdownlint-cli --fix "**/*.md"
+
+  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-markdown-task/Taskfile.yml
+  markdown:lint:
+    desc: Check for problems in Markdown files
+    cmds:
+      - npx markdownlint-cli "**/*.md"
+
+  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/poetry-task/Taskfile.yml
+  poetry:install-deps:
+    desc: Install dependencies managed by Poetry
+    cmds:
+      - poetry install --no-root
 
   protoc:
     desc: Lint, format and compile protobuf definitions
@@ -200,6 +265,24 @@ tasks:
       - git add -N ./i18n/data
       - git diff --exit-code ./i18n/data &> /dev/null || { cd ./i18n && rice embed-go; }
 
+  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-mkdocs-task/Taskfile.yml
+  website:check:
+    desc: Check whether the MkDocs-based website will build
+    deps:
+      - task: docs:generate
+      - task: poetry:install-deps
+    cmds:
+      - poetry run mkdocs build --strict
+
+  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-mkdocs-task/Taskfile.yml
+  website:serve:
+    desc: Run website locally
+    deps:
+      - task: docs:generate
+      - task: poetry:install-deps
+    cmds:
+      - poetry run mkdocs serve
+
 vars:
   PROJECT_NAME: "arduino-cli"
   DIST_DIR: "dist"
@@ -238,8 +321,3 @@ vars:
   GOLINTBIN:
     sh: go list -f {{"{{"}}".Target{{"}}"}}" golang.org/x/lint/golint
   GOLINTFLAGS: "-min_confidence 0.8 -set_exit_status"
-  # docs versioning
-  DOCS_VERSION: dev
-  DOCS_ALIAS: ""
-  DOCS_REMOTE: "origin"
-  PRETTIER: prettier@2.0.5
